huggingface_hub_token: Insert token here
openai_key: Insert api key here
batch_size: 8
cache_dir: /pfs/work9/workspace/scratch/hd_go226-models
do_sample: true
judgement_files_directory: debug/judgements
excel_output_directory: debug/excel_overviews
run_info_csv_path: debug/job_infos.csv