huggingface_hub_token: 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
openai_key: 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
batch_size: 8
cache_dir: /pfs/work9/workspace/scratch/hd_go226-models
do_sample: true
judgement_files_directory: debug/judgements
excel_output_directory: debug/excel_overviews
run_info_csv_path: debug/job_infos.csv