import os
import re
from abc import ABC, abstractmethod
from string import ascii_letters, digits
from typing import Dict, List, Optional

from google import genai
from google.genai.types import GenerateContentConfig
from huggingface_hub import repo_exists
from openai import OpenAI

MAX_OUTPUT_TOKENS = 512


class Model(ABC):

    def __init__(self, model_name_or_path: str):
        self.model_name_or_path = model_name_or_path

    @abstractmethod
    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
    ) -> List[List[str]]:
        """
        Input is a list of system prompts and a list of input texts.
        Each system prompt corresponds to a message in the input_texts list.
        The method should return a list of lists, where each inner list
        contains the generated responses for each message.
        The inner list is the amount of responses generated by the model.
        """
        pass

    def apply_chat_template(
        self,
        input_text: str,
        system_prompt: str = "",
    ) -> List[Dict[str, str]]:
        """
        OpenAI uses this template directly.
        HuggingFace models have a method .apply_chat_template() themselves,
        that takes the output of this method and applies it to the model.
        Gemini models need to override this method to apply the chat template,
        since they can not be passed a role-based chat template like OpenAI or HuggingFace.
        """
        input_texts = []
        if system_prompt:
            input_texts.append({"role": "system", "content": system_prompt})
        input_texts.append({"role": "user", "content": input_text})
        return input_texts

    def get_response_data(
        self,
        responses: List[List[str]],
    ) -> Dict[str, List[List[str]]]:
        """
        Extracts the response data from the generated responses.
        The method should return a dictionary with the following structure:
        {
            "output": List[List[str]] # all generated outputs
            "extracted_answers": List[List[str]] # extracted answers
        }
        """
        all_outputs = []
        all_extracted_answers = []

        # responses is a list of lists,
        # the inner list is num_generations responses for each input text
        # we call this a response_batch here, it has nothing do with the batch size
        for response_batch in responses:
            outputs = []
            extracted_answers = []
            for response in response_batch:
                outputs.append(response)
                extracted_answer = self.extract_answer(response)
                extracted_answers.append(extracted_answer)
            all_outputs.append(outputs)
            all_extracted_answers.append(extracted_answers)

        return {
            "output": all_outputs,
            "extracted_answers": all_extracted_answers,
        }

    def extract_answer(self, text: str) -> str | None:
        """
        Given a text, extract the answer from it.
        The answer can be one of "Answer1", "Answer2", or "Tie".
        If the answer is ambiguous (e.g. both "Answer1" and "Answer2" are present), return None.
        If no answer is found, return None.
        """

        if not text:
            return None
        pattern = r"^\s*\S*(Answer1|Answer2|Tie)\S*\s*$"
        matches = []
        for line in text.split("\n"):
            match = re.match(pattern, line, flags=re.IGNORECASE)
            if match:
                matches.append(match.group(1).lower())
        if not matches:
            return None
        unique_answers = set(matches)
        if len(unique_answers) > 1:
            return None
        return matches[-1]


class vLLMModel(Model):
    def __init__(self, model_name_or_path: str, config: dict, tasks: Optional[dict]=None):
        from vllm import LLM, SamplingParams

        # from vllm.sampling_params import BeamSearchParams
        # from torch.cuda import device_count

        super().__init__(model_name_or_path)

        if config.get("model_zipped"):
            # unzip the model to TMPDIR if it is zipped
            import zipfile

            with zipfile.ZipFile(model_name_or_path, "r") as zip_ref:
                tmpdir = os.environ.get("TMPDIR")
                if tmpdir is None:
                    raise ValueError("TMPDIR environment variable not set.")
                unzip_path = os.path.join(
                    tmpdir, os.path.basename(model_name_or_path) + "_unzipped"
                )
                zip_ref.extractall(unzip_path)
                model_name_or_path = unzip_path

        config_mode = "mistral" if "mistral" in model_name_or_path else "auto"

        # Provide default values if tasks is not provided
        if tasks is None:
            tasks = {
                "vllm_parameters": {"tensor_parallel_size": 2},
                "model_parameters": {"dtype": "bfloat16", "num_generations": 1, "max_output_tokens": MAX_OUTPUT_TOKENS},
                "sampling_parameters": {}
            }

        self.llm = LLM(
            model=model_name_or_path,
            tensor_parallel_size=tasks["vllm_parameters"].get(
                "tensor_parallel_size", 2
            ),  # device_count()
            dtype=tasks["model_parameters"].get("dtype", "bfloat16"),
            max_model_len=4096,
            download_dir=config.get("cache_dir", None),
            tokenizer_mode=config_mode,
            load_format=config_mode,
            config_format=config_mode,
            limit_mm_per_prompt={"image": 0},  # disable multimodal for this project
        )

        # Clean up sampling parameters by removing None values
        sampling_params = tasks.get("sampling_parameters", {})
        for key, item in list(sampling_params.items()):
            if item is None:
                del sampling_params[key]

        # Decide whether to use sampling or beam search
        self.has_sampling_param = any(
            k in sampling_params for k in ("temperature", "top_p", "min_p", "top_k")
        )

        # if self.has_sampling_param:
        # Use SamplingParams when any sampling parameter is set
        self.sampling_params = SamplingParams(
            # TODO: (also see in generate method) Decide whether we want to continue using our own sampling params
            # or just use the sampling params recommended by the model creators, which get loaded automatically if we don't set them here
            # temperature=sampling_params.get("temperature", 0.0),
            # top_p=sampling_params.get("top_p", 1.0),
            # min_p=sampling_params.get("min_p", 0.0),
            # top_k=sampling_params.get("top_k", -1),
            n=tasks["model_parameters"].get("num_generations", 3),
            max_tokens=tasks["model_parameters"].get(
                "max_output_tokens", MAX_OUTPUT_TOKENS
            ),
        )
        # else:
        #     self.beam_search_params = BeamSearchParams(
        #         beam_width=tasks["model_parameters"].get("num_generations", 3),
        #         max_tokens=tasks["model_parameters"].get(
        #             "max_output_tokens", MAX_OUTPUT_TOKENS
        #         ),
        #     )

    def format_inputs(
        self,
        input_texts: List[str],
        system_prompts: List[str],
    ) -> list[List[Dict[str, str]]]:
        messages_batch = [
            self.apply_chat_template(input_text, sys_prompt)
            for input_text, sys_prompt in zip(input_texts, system_prompts)
        ]
        return messages_batch

    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
    ) -> List[List[str]]:
        inputs = self.format_inputs(input_texts, system_prompts)
        # if self.has_sampling_param:
        outputs = self.llm.chat(inputs, sampling_params=self.sampling_params)
        # outputs has this format: outputs[j].output.outputs[i].text
        outputs = [
            [output.text for output in generation.outputs] for generation in outputs
        ]
        # else:
        # TODO: Decide whether we want to continue using beam search or just use the sampling params recommended by the model creators
        # beam_inputs = [{"prompt": text} for text in inputs]
        # outputs = self.llm.beam_search(beam_inputs, self.beam_search_params)
        # # outputs has this format: outputs[j].output.outputs[i].text
        # outputs = [[output.text for output in generation.outputs] for generation in outputs]

        return outputs

class OpenAIModel(Model):
    def __init__(self, model_name_or_path: str, api_key: str):
        super().__init__(model_name_or_path)
        self.openai_client = OpenAI(api_key=api_key)

    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
        num_generations: int = 1,
        **kwargs,
    ) -> List[List[str]]:
        if kwargs.get("use_batch_api", False):
            raise NotImplementedError(
                "Batch API is not implemented for OpenAI models yet."
            )
        else:
            responses = []
            for input_text, system_prompt in zip(input_texts, system_prompts):
                message = self.apply_chat_template(input_text, system_prompt)
                response_batch = []
                for _ in range(num_generations):
                    response = self.openai_client.responses.create(
                        model=self.model_name_or_path,
                        input=message,  # type: ignore
                        max_output_tokens=kwargs.get("max_output_tokens", MAX_OUTPUT_TOKENS),  # type: ignore
                    )
                    response_batch.append(response.output_text)
                responses.append(response_batch)
            # save additional metadata as attribute if necessary
            if kwargs.get("additional_information", True):
                self.exact_model = response.model
                self.temperature = response.temperature
            
            return responses
        
class GeminiModel(Model):
    def __init__(self, model_name_or_path: str, api_key: str):
        super().__init__(model_name_or_path)
        self.client = genai.Client(api_key=api_key)

    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
        num_generations: int = 1,
        **kwargs,
    ) -> List[List[str]]:
        responses = []
        for input_text, system_prompt in zip(input_texts, system_prompts):
            if system_prompt:
                config = GenerateContentConfig(
                    max_output_tokens=kwargs.get(
                        "max_output_tokens", MAX_OUTPUT_TOKENS
                    ),
                    system_instruction=system_prompt,
                )
            else:
                config = GenerateContentConfig(
                    max_output_tokens=kwargs.get(
                        "max_output_tokens", MAX_OUTPUT_TOKENS
                    ),
                )

            response_batch = []
            for _ in range(num_generations):
                response = self.client.models.generate_content(
                    model=self.model_name_or_path, contents=input_text, config=config
                )
                response_batch.append(response.text)
            responses.append(response_batch)

        return responses
    
class ClaudeModel(Model):
    def __init__(self, model_name_or_path: str, api_key: str):
        super().__init__(model_name_or_path)
        import anthropic

        self.claude_client = anthropic.Anthropic(api_key=api_key)

    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
        num_generations: int = 1,
        **kwargs,
    ) -> List[List[str]]:
        if kwargs.get("use_batch_api", False):
            raise NotImplementedError(
                "Batch API is not implemented for Claude models yet."
            )
        else:
            responses = []
            for input_text, system_prompt in zip(input_texts, system_prompts):
                message = self.apply_chat_template(input_text)
                response_batch = []
                for _ in range(num_generations):
                    response = self.claude_client.messages.create(
                        model=self.model_name_or_path,
                        system=system_prompt,
                        messages=message,  # type: ignore
                        max_tokens=kwargs.get("max_output_tokens", MAX_OUTPUT_TOKENS),
                    )
                    response_batch.append(response.content[0].text)  # type: ignore
                responses.append(response_batch)

            return responses


class RandomAnswer(Model):
    def __init__(self):
        """
        This model is for debugging purposes only.
        It randomly chooses between "Answer1", "Answer2", and "Tie" as the output.
        This is useful to test the pipeline without needing the hardware to run a big LLM
        or using API credits.
        """
        super().__init__("random_choice_model")

    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
        num_generations: int = 1,
        **kwargs,
    ) -> List[List[str]]:
        from random import choice

        responses = []
        for input_text, system_prompt in zip(input_texts, system_prompts):
            response_batch = []
            for _ in range(num_generations):
                response = choice(
                    ascii_letters + digits + "Answer1" + "Answer2" + "Tie"
                )
                response_batch.append(response)
            responses.append(response_batch)
        return responses

def get_model(model_name_or_path: str, config: dict, tasks: Optional[dict]=None) -> Model:
    if repo_exists(
        model_name_or_path, repo_type="model", token=config.get("huggingface_hub_token")
    ):
        # Some models are restricted and require a token to access
        from huggingface_hub import login

        if not (token := config.get("huggingface_hub_token")):
            raise ValueError(
                "Hugging Face Hub token is required for Hugging Face models."
            )
        login(token)

        return vLLMModel(model_name_or_path, config, tasks)
    elif "gpt" in model_name_or_path:
        if not (api_key := config.get("openai_key")):
            raise ValueError("API key is required for OpenAI models.")
        return OpenAIModel(model_name_or_path, api_key)

    elif "gemini" in model_name_or_path:
        if not (api_key := config.get("gemini_key")):
            raise ValueError("API key is required for Gemini models.")
        return GeminiModel(model_name_or_path, api_key)
    elif "claude" in model_name_or_path:
        if not (api_key := config.get("claude_key")):
            raise ValueError("API key is required for Claude models.")
        return ClaudeModel(model_name_or_path, api_key)
    elif model_name_or_path == "RandomAnswer":
        return RandomAnswer()
    else:
        raise ValueError(f"Model {model_name_or_path} not supported.")
